from app.models.usuario import Usuario
from app.models.competicion import Competicion
from app.models.equipo_real import EquipoReal
from app.models.jugador import Jugador
from app.models.liga_fantasy import LigaFantasy
from app.models.participante_liga import ParticipanteLiga
from app.models.equipo_fantasy import EquipoFantasy
from app.models.plantilla_equipo import PlantillaEquipo
from app.models.jornada import Jornada